version: '3.8'

services:
  database:
    platform: linux/x86_64
    image: mysql:8
    ports:
        - "33061:3306"
    command: --init-file /data/application/init.sql
    restart: always
    volumes:
        - ./init.sql:/data/application/init.sql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    networks:
      - prova

  app:
    image: luby-cash
    depends_on:
      - "database"
    build: .
    ports: 
      - '3333:3333'
    volumes:
      - .:/app
    restart: on-failure
    environment:
     - HOST=app
     - PORT=3333
     - NODE_ENV=development
     - DRIVE_DISK=local
     - DB_CONNECTION=mysql
     - TZ=America/Campo_Grande
     - SMTP_HOST=smtp.mailtrap.io
     - SMTP_PORT=2525
     - SMTP_USERNAME=58084adc95c9f0
     - SMTP_PASSWORD=6c236dd4ff89aa
     - CACHE_VIEWS=false
     - MYSQL_HOST=database
     - MYSQL_PORT=3306
     - MYSQL_USER=root
     - MYSQL_PASSWORD=provams
     - MYSQL_DB_NAME=lubycash
     - KAFKA_CONNECTION=kafka:29092
     - MS_CLIENTS_BASE_URL=http://clients:4000
    links:
      - database
    networks:
      - prova
  
networks:
  prova:
    name: prova
    external: true